# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Bug report
description: File a bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: Thank you very much for submitting feedback to Fury.
  - type: checkboxes
    attributes:
      label: Search before asking
      description: >
        Please make sure to search in the [issues](https://github.com/apache/fury/issues) first to see whether the same issue was reported already.
      options:
        - label: >
            I had searched in the [issues](https://github.com/apache/fury/issues) and found no similar issues.
          required: true
  - type: textarea
    attributes:
      label: Version
      description: >
        Please provide the versions of Fury, OS, and others such as JDK/Python/Gcc/Clang/Go/NodeJS if they are used.
        If Fury is the unstable version, please input commit id.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component(s)
      multiple: true
      options:
        - Java
        - JavaScript
        - Python
        - Go
        - C++
        - Rust
        - C#
        - Doc
        - Benchmark
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal reproduce step
      description: Please try to give reproducing steps to facilitate quick location of the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you see instead?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything Else?
  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?
      description: >
        We very much look forward to developers or users to help solve Fury problems together.
        If you are willing to submit a PR to fix this problem, please tick it.
      options:
        - label: I'm willing to submit a PR!
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
